// Generated by CoffeeScript 1.10.0
(function() {
  var MatchMaker, Utils, matchmakerSocket, net;

  net = require('net');

  Utils = require("./utils");

  matchmakerSocket = net.createServer();

  MatchMaker = (function() {
    function MatchMaker(listener) {
      this.listener = listener;
      this.utils = new Utils;
      this.N = this.utils.N;
      this.HOST = this.utils.HOST;
      this.MATCHMAKER_PORT = this.utils.MATCHMAKER_PORT;
      this.server = matchmakerSocket;
      this.server.on('data', function(data) {
        return this.receivedMessage(data);
      });
      this.server.listen(this.MATCHMAKER_PORT);
    }

    MatchMaker.prototype.checkIfNumbersValid = function(numbers) {
      var i, len, number;
      if (numbers.length !== this.N) {
        return false;
      }
      for (i = 0, len = numbers.length; i < len; i++) {
        number = numbers[i];
        if (number < 0) {
          return false;
        } else if (number > 1) {
          return false;
        } else if (this.utils.numberOfDecimals(number) > 4) {
          return false;
        }
      }
      return true;
    };

    MatchMaker.prototype.makeNumsValid = function(numbers) {
      var additionalNumsNeedded, i, index, j, len, num, ref;
      if (numbers.length > this.N) {
        numbers = numbers.slice(0, this.N - 1);
      } else if (numbers.length < this.N) {
        additionalNumsNeedded = this.N - numbers.length;
        for (i = 0, ref = additionalNumsNeeded; 0 <= ref ? i <= ref : i >= ref; 0 <= ref ? i++ : i--) {
          numbers.push(0);
        }
      }
      for (index = j = 0, len = numbers.length; j < len; index = ++j) {
        num = numbers[index];
        if (num < 0) {
          numbers[index] = 0;
        } else if (num > 1) {
          numbers[index] = 1;
        }
      }
      return numbers;
    };

    MatchMaker.prototype.receivedMessage = function(message) {
      var valid;
      this.currentNums = this.utils.convertStringToNumArray(message);
      valid = this.checkIfNumbersValid(this.currentNums);
      if (valid) {
        this.lastValidNums = this.currentNums;
      } else {
        if (typeof this.lastValidNums === 'undefined') {
          this.currentNums = this.utils.convertStringToNumArray(message, 4);
          this.lastValidNums = this.makeNumsValid(this.currentNums);
        }
      }
      return this.listner.receivedCandidateFromMM(this.lastValidNums);
    };

    MatchMaker.prototype.sendMessage = function(message) {
      return this.server.write(message);
    };

    return MatchMaker;

  })();

  module.exports = MatchMaker;

}).call(this);
