// Generated by CoffeeScript 1.10.0
(function() {
  var HOST, MATCHMAKER_PORT, N, PLAYER_PORT, Utils, client, connectingPort, createRandomCandidate, lastReceivedNumbers, lastReceivedScore, makeCandidate, net, parseData, parseMultipleCandidates, parseSingleCandidate, utils;

  console.log("In matchMaker Client");

  net = require('net');

  Utils = require("./utils");

  utils = new Utils;

  N = utils.getN();

  HOST = utils.getHOST();

  MATCHMAKER_PORT = utils.getMATCHMAKER_PORT();

  PLAYER_PORT = utils.getPLAYER_PORT();

  console.log("Matchmaker Port " + MATCHMAKER_PORT);

  connectingPort = {
    port: MATCHMAKER_PORT
  };

  lastReceivedNumbers = [];

  lastReceivedScore = 0;

  parseData = function(data) {
    if (data.split("\n").length > 10) {
      return parseMultipleCandidates(data);
    } else {
      return parseSingleCandidate(data);
    }
  };

  parseSingleCandidate = function(data) {
    var index, k, lastReceivedCandidate, ref, splitData;
    lastReceivedCandidate = [];
    splitData = data.split(/\D/);
    for (index = k = 0, ref = N - 1; 0 <= ref ? k <= ref : k >= ref; index = 0 <= ref ? ++k : --k) {
      lastReceivedNumber.push(splitData[index]);
    }
    return lastReceivedScore = splitData[N + 2];
  };

  parseMultipleCandidates = function(data) {
    var currentCandidate, currentCandidateScore, i, j, k, l, ref, ref1, splitData, totalCandidates, totalCandidatesScores, totalIterations, valuesPerCandidate;
    totalCandidates = [];
    totalCandidatesScores = [];
    currentCandidate = [];
    currentCandidateScore = 0;
    splitData = data.split(/\D/);
    valuesPerCandidate = N + 4;
    totalIterations = splitData.length / valuesPerDandidate;
    for (i = k = 1, ref = totalIterations; 1 <= ref ? k <= ref : k >= ref; i = 1 <= ref ? ++k : --k) {
      for (j = l = 0, ref1 = N - 1; 0 <= ref1 ? l <= ref1 : l >= ref1; j = 0 <= ref1 ? ++l : --l) {
        currentCandidate.push(splitData[j]);
      }
      currentCandidateScore = splitData[N + 2];
      totalCandidates.push(currentCandidate);
      totalCandidatesScores.push(currentCandidateScore);
      splitData.splice(0, valuesPerCandidate);
    }
    console.log("Total Candidates: ");
    console.log(totalCandidates);
    console.log("Total Scores: ");
    return console.log(totalCandidatesScores);
  };

  makeCandidate = function() {
    var randomCandidate;
    return randomCandidate = createRandomCandidate();
  };

  createRandomCandidate = function() {
    var candidate, k, ref, weight;
    candidate = [];
    for (weight = k = 1, ref = N; 1 <= ref ? k <= ref : k >= ref; weight = 1 <= ref ? ++k : --k) {
      candidate.push(Math.random().toFixed(4));
    }
    return candidate;
  };

  client = net.connect(connectingPort, function() {
    return console.log("MM Client Connected");
  });

  client.on('data', function(data) {
    var candidate, candidateString;
    console.log("MM Client Received Data");
    if (data === !"gameover") {
      console.log("MM Client sending data");
      parseData(data);
      candidate = makeCandidate();
      candidateString = utils.convertNumArrayToFormattedString(candidate);
      return client.write(candidateString);
    }
  });

}).call(this);
