// Generated by CoffeeScript 1.10.0
(function() {
  var HOST, MATCHMAKER_PORT, N, PLAYER_PORT, Utils, client, connectingPort, createBasicCandidate, lastReceivedNumbers, lastReceivedScore, makeCandidate, net, utilsL;

  console.log("In player Client");

  net = require('net');

  Utils = require("./utils");

  this.utils = new Utils;

  utilsL = this.utils;

  N = this.utils.N;

  HOST = this.utils.HOST;

  MATCHMAKER_PORT = this.utils.MATCHMAKER_PORT;

  PLAYER_PORT = this.utils.PLAYER_PORT;

  lastReceivedNumbers = [];

  lastReceivedScore = 0;

  connectingPort = {
    port: PLAYER_PORT
  };

  makeCandidate = function() {
    var basicCandidate;
    return basicCandidate = createBasicCandidate();
  };

  createBasicCandidate = function() {
    var candidate, i, index, negativeWeightValue, positiveWeightValue, ref, value, weightValue;
    candidate = [];
    weightValue = 1 / (N / 2);
    weightValue = weightValue.toFixed(2);
    weightValue = parseFloat(weightValue);
    negativeWeightValue = 0.0;
    positiveWeightValue = 0.0;
    for (index = i = 1, ref = N; 1 <= ref ? i <= ref : i >= ref; index = 1 <= ref ? ++i : --i) {
      if (index % 2 === 0) {
        candidate.push(weightValue);
        positiveWeightValue = weightValue + positiveWeightValue;
      } else {
        candidate.push(-weightValue);
        negativeWeightValue = weightValue + negativeWeightValue;
      }
    }
    positiveWeightValue = positiveWeightValue.toFixed(2);
    negativeWeightValue = negativeWeightValue.toFixed(2);
    if (positiveWeightValue < 1) {
      value = candidate[1];
      value += 1 - positiveWeightValue;
      candidate[1] = value.toFixed(2);
    } else if (positiveWeightValue > 1) {
      value = candidate[1];
      value -= positiveWeightValue - 1;
      value.toFixed(2);
      candidate[1] = value.toFixed(2);
    }
    if (negativeWeightValue < 1) {
      value = candidate[0];
      value -= 1 - negativeWeightValue;
      value.toFixed(2);
      candidate[0] = value.toFixed(2);
    } else if (positiveWeightValue > 1) {
      value = candidate[0];
      value += negativeWeightValue - 1;
      value.toFixed(2);
      candidate[0] = value.toFixed(2);
    }
    return candidate;
  };

  client = net.connect(connectingPort, function() {
    var candidate, candidateString;
    console.log("Player client connected on port " + connectingPort.port);
    candidate = makeCandidate();
    candidateString = utilsL.convertNumArrayToFormattedString(candidate);
    return client.write(candidateString);
  });

  client.on('data', function(data) {
    var candidate, candidateString;
    data = data.toString();
    if (data !== "gameover") {
      candidate = makeCandidate();
      candidateString = utilsL.convertNumArrayToFormattedString(candidate);
      console.log("Player Client sending data");
      return client.write(candidateString);
    } else {
      return console.log("GAMEOVER");
    }
  });

}).call(this);
