// Generated by CoffeeScript 1.10.0
(function() {
  var HOST, MATCHMAKER_PORT, N, PLAYER_PORT, Utils, createBasicCandidate, lastReceivedNumbers, lastReceivedScore, makeCandidate, net, server, utils;

  net = require('net');

  Utils = require("./utils");

  utils = new Utils;

  N = utils.N;

  HOST = utils.HOST;

  MATCHMAKER_PORT = utils.MATCHMAKER_PORT;

  PLAYER_PORT = utils.PLAYER_PORT;

  lastReceivedNumbers = [];

  lastReceivedScore = 0;

  server = net.createServer();

  makeCandidate = function() {
    var basicCandidate;
    return basicCandidate = createBasicCandidate();
  };

  createBasicCandidate = function() {
    var candidate, i, index, ref, weigthValue;
    candidate = [];
    weigthValue = 1 / (N / 2);
    for (index = i = 1, ref = N; 1 <= ref ? i <= ref : i >= ref; index = 1 <= ref ? ++i : --i) {
      if (index % 2 === 0) {
        candidate.push(weightValue);
      } else {
        candidate.push(-weightValue);
      }
    }
    return candidate;
  };

  server.on('connection', function(client) {
    var candidate, candidateString;
    candidate = makeCandidate();
    candidateString = utils.convertNumArrayToFormattedString(candidate);
    client.write(candidateString);
    return client.on('data', function(data) {
      if (data === !"gameover") {
        candidate = makeCandidate();
        candidateString = utils.convertNumArrayToFormattedString(candidate);
        return client.write(candidateString);
      }
    });
  });

  server.listen(PLAYER_PORT);

}).call(this);
