// Generated by CoffeeScript 1.10.0
(function() {
  var Utils;

  Utils = (function() {
    function Utils() {}

    Utils.N = 20;

    Utils.HOST = '127.0.0.1';

    Utils.MATCHMAKER_PORT = 6969;

    Utils.PLAYER_PORT = 9696;

    Utils.prototype.numberOfDecimals = function(number) {
      number = number.toString();
      return (number.split('.')[1] || []).length;
    };

    Utils.prototype.convertStringToNumArray = function(numberString, decimalPoints) {
      var i, index, j, numberArray, ref, ref1, stringArray;
      if (decimalPoints == null) {
        decimalPoints = 0;
      }
      numberArray = [];
      if (numberString) {
        stringArray = numberString.split(" ");
        if (decimalPoints === 0) {
          for (index = i = 0, ref = this.N - 1; 0 <= ref ? i <= ref : i >= ref; index = 0 <= ref ? ++i : --i) {
            numberArray.push(parseFloat(stringArray[index]));
          }
        } else {
          for (index = j = 0, ref1 = this.N - 1; 0 <= ref1 ? j <= ref1 : j >= ref1; index = 0 <= ref1 ? ++j : --j) {
            numberArray.push(parseFloat(stringArray[index]).toFixed(decimalPoints));
          }
        }
        return numberArray;
      } else {
        return console.log("We are splitting an undefined");
      }
    };

    Utils.prototype.convertNumArrayToFormattedString = function(numArray) {
      var i, len, num, returnString;
      returnString = "";
      for (i = 0, len = numArray.length; i < len; i++) {
        num = numArray[i];
        returnString += num + " ";
      }
      return returnString;
    };

    return Utils;

  })();

  module.exports = Utils;

}).call(this);
