// Generated by CoffeeScript 1.10.0
(function() {
  var Utils;

  Utils = (function() {
    function Utils() {}

    Utils.N = 20;

    Utils.HOST = '127.0.0.1';

    Utils.MATCHMAKER_PORT = 6969;

    Utils.PLAYER_PORT = 9696;

    Utils.prototype.numberOfDecimals = function(number) {
      number = number.toString();
      return (number.split('.')[1] || []).length;
    };

    Utils.prototype.convertStringToNumArray = function(numberString, decimalPoints) {
      var index, numberArray, stringArray, value;
      if (decimalPoints == null) {
        decimalPoints = 0;
      }
      numberArray = [];
      if (numberString) {
        stringArray = numberString.split(" ");
        if (decimalPoints === 0) {
          numberArray[index] = (function() {
            var i, len, results;
            results = [];
            for (index = i = 0, len = stringArray.length; i < len; index = ++i) {
              value = stringArray[index];
              results.push(parseFloat(value));
            }
            return results;
          })();
        } else {
          numberArray[index] = (function() {
            var i, len, results;
            results = [];
            for (index = i = 0, len = stringArray.length; i < len; index = ++i) {
              value = stringArray[index];
              results.push(parseFloat(value).toFixed(decimalPoints));
            }
            return results;
          })();
        }
        return numberArray;
      } else {
        return console.log("We are splitting an undefined");
      }
    };

    return Utils;

  })();

  module.exports = Utils;

}).call(this);
